name: Scrape and Generate Wordclouds

permissions:
  contents: write

on:
  workflow_dispatch:  # Manuell auslösbar über GitHub
  schedule:
    - cron: '15 16 * * *'   # 17:10 MESZ (heute)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Wichtig für Push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader stopwords
          python -m spacy download de_core_news_sm

      - name: Run scraper script
        run: |
          python main.py  # Passe den Namen an, falls dein Script anders heißt

      - name: Configure git for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push generated images if any change
        run: |
          git add static/images/
          if ! git diff --cached --quiet; then
            git commit -m "chore: update generated wordcloud images [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
