name: Scrape and Generate Wordclouds

permissions:
  contents: write

on:
  workflow_dispatch:  # Manuell auslösbar über GitHub
  schedule:
    - cron: '05 07 * * *'  # 09:05 Uhr MESZ / 08:05 Uhr MEZ

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader stopwords
          python -m spacy download de_core_news_sm

      - name: Run scraper script
        run: python main.py  # Passe den Dateinamen an, falls abweichend

      - name: Configure git for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push generated images if any change
        id: commit_step
        run: |
          mkdir -p static/images
          git add static/images/ || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: update generated wordcloud images [skip ci]"
            git push
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger Render Deploy Hook
        if: steps.commit_step.outputs.changes == 'true'
        run: |
          curl -X POST https://api.render.com/deploy/srv-d19if37gi27c73ct83fg?key=FJCiFHjK9kc
